version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:15.10.2-ee.0'
    restart: on-failure:1
    hostname: 'arkonautom.eu'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://arkonautom.eu'
        letsencrypt['contact_emails'] = ['arkonautom@gmail.com'] # Optional
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - type: volume
        source: gitlab-config
        target: /etc/gitlab
      - type: volume
        source: gitlab-data
        target: /var/opt/gitlab
      - type: volume
        source: gitlab-logs
        target: /var/log/gitlab
    shm_size: '256m'
  gitlab-runner:
    image: 'gitlab/gitlab-runner:v15.10.1'
    restart: on-failure:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: gitlab-runner_config
        target: /etc/gitlab-runner
      - type: volume
        source: gitlab-runner_home
        target: /home/gitlab-runner
  sonarqube:
    image: 'sonarqube:9.9.0-community'
    #restart: on-failure:1
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar-db
    volumes:
      - type: volume
        source: sonarqube_data
        target: /opt/sonarqube/data
      - type: volume
        source: sonarqube_extensions
        target: /opt/sonarqube/extensions
      - type: volume
        source: sonarqube_logs
        target: /opt/sonarqube/logs
  sonarqube-db:
    image: 'postgres:15.2'
    restart: on-failure:1
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar-db
      POSTGRES_DB: sonarqube
    volumes:
      - type: volume
        source: sonarqube-db
        target: /var/lib/postgresql
      - type: volume
        source: sonarqube-db_data
        target: /var/lib/postgresql/data
volumes:
  gitlab-config:
    external: true
  gitlab-data:
    external: true
  gitlab-logs:
    external: true
  gitlab-runner_config:
    external: true
  gitlab-runner_home:
    external: true
  sonarqube-db:
    external: true
  sonarqube-db_data:
    external: true
  sonarqube_data:
    external: true
  sonarqube_extensions:
    external: true
  sonarqube_logs:
    external: true